# Generated by Django 3.1.1 on 2020-09-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App__Todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='TaskModel',
        ),
    ]
